name: Flujo_trabajo # nombre del flujo de trabajo

# Evento que activa el flujo de trabajo
on:
  push:
    branches:
      - main
# El flujo se ejecutar치 cada vez que haya un push a la rama main.

jobs:
  # Identificador del trabajo (job) dentro del flujo de trabajo.
  example-job:
    # El job se ejecutar치 en un runner con Ubuntu.
    runs-on: ubuntu-latest

    # Pasos del job
    steps:
      # Checkout del c칩digo
      - name: Checkout code
        uses: actions/checkout@v3
      # Este paso clona el c칩digo del repo en el runner.

      # Uso del Personal Access Token guardado como secreto PATH_SECRET
      - name: Use Personal Access Token
        # Ejecuta el comando curl para realizar una llamada a la API de GitHub.
        run: |
          curl -H "Authorization: Bearer ${{ secrets.PATH_SECRET }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/user/repos
        # PATH_SECRET debe estar creado en: Settings > Secrets and variables > Actions
